# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('description', models.CharField(default=None, max_length=200)),
                ('price1', models.CharField(default=None, max_length=20)),
                ('price2', models.CharField(default=None, max_length=20)),
                ('price3', models.CharField(default=None, max_length=20)),
                ('sort', models.PositiveIntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subtext', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='api.Menu'),
        ),
    ]
