# Generated by Django 2.0.1 on 2018-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subtext', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
