# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180124_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=200)),
                ('price1', models.CharField(default=None, max_length=20)),
                ('price2', models.CharField(default=None, max_length=20)),
                ('price3', models.CharField(default=None, max_length=20)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Menu')),
            ],
        ),
    ]
